name = "OpenBP"
uuid = "0a670736-3c0f-4040-b7b8-ebfdc8633ef1"
authors = ["anthonypetertc <anthonypetertc@hotmail.com>"]
version = "0.1.0"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
OpenSystemsTools = "523c94b8-8449-48a9-9e5b-99d75234c7ae"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
